package model.constant;

public enum MessageType {
    FIND_SERVER_BROADCAST,
    SERVER_BROADCAST_RESPONSE,

    SET_USERNAME,
    SET_CLIENT_ID,

    PAINT_DATA,
    PAINT_BOARD,
    CHAT_MESSAGE,
    CLIENT_LIST,

    REQUEST_PAINT_BOARD,
    CLEAR_PAINT_BOARD,
    REQUEST_CLIENT_LIST,
}
